#!/bin/bash

CURR_HOST=`hostname`
PID=`cat pids/dbs$CURR_HOST.pid`


if ! kill -0 $PID > /dev/null 2>&1;
then
	echo "Database down -- restarting..."
	./startDbLocal $1
	echo "OK"
else # the process is running
	echo "Database OK"
fi
