#!/bin/bash

# Start server locally
echo 'Compiling and starting up servers'
cd ../shellScripts
bash compilePrograms
bash startServiceLocal $1

# Wait for server to startup
echo "waiting 5 seconds"
sleep 5

curl -X PUT 'http://localhost:8080/?short=AAA&long=http://hello'
sleep 1

curl -X GET 'http://localhost:8080/AAA'
sleep 1

# Stop server locally
echo "Stopping servers"
cd ../shellScripts
bash stopServiceLocal $1